### ISSUE TITLE
[Bug] Can't post pictures anymore on kohlchan.net

### ISSUE THREAD

**Issue by gruzefix** [SthephanShinkufag/Dollchan-Extension-Tools#1389]
I can't seem to post pictures from my hard drive (or from links, for that matter) to KC anymore since maybe last November or so. Dollchan spits out

```
Internal error:
TypeError: dc.body is undefined
    at getSubmitError (Dollchan%20Extension%20Tools.user.js?id=[redacted])
    at checkUpload (Dollchan%20Extension%20Tools.user.js?id=[redacted])
```

I don't know if the redacted part is important, if it is please PM me, don't know if that string contains sensitive info about me. I initially thought it had to do with me using a VPN most of the time, but it won't work using my native IP either - and I've been using a VPN (the same, to be honest) for several years by now.

It works fine when I turn off Dollchan.

FF 84.0.2 (64-bit), latest Win 10 Pro, Tampermonkey 4.11.6120, Dollchan v20.3.17 (ESNext)

**Comment by ganego** [comment]
There is a dedicated KC thread: #1332  
Install this: https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/src/Dollchan_Extension_Tools.es6.user.js  
I know there is a bug that does not show the captcha when writing a post and KC wants a captcha because it does not like your IP, but I have no idea how to fix this. But that bug silently discards your post.  

In the other thread there was also someone with that bug and he also used Tampermonkey. I use Violentmonkey with FF and have no issues with picture uploads (neither from disk nor from the internet).

Can you modify the script the following way:  
- Search for `function checkUpload`
- After `const isDocument = data instanceof HTMLDocument;` add: `alert(isDocument);`
- Before `error = getSubmitError(_data);` add a new line with: `alert(1);`
- Before `error = getSubmitError(data);` add a new line with: `alert(2);`

Then before DC crashes popups should appear. The first one says either "true" or "false" and the next one "1" or "2".  
And test Violentmonkey.

**Comment by SthephanShinkufag** [comment]
Damn, I racked my brains for so long how to make kohlchan to show me a captcha so that I could implement it in Dollchan. And all I have to do is to visit from under the VPN. Thanks guys, soon will be support for captcha on kohlchan!

**Comment by ganego** [comment]
I mean, it's not like I told you so https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/issues/1332#issuecomment-612587442  :))) 
I never knew how to fix this, so my solution was copying each post to the clipboard via DC, so I won't lose it when getting the captcha, then manually going to `.../blockBypass.js` and solve it without having to disable DC. Yay for crude hacks.

**Comment by SthephanShinkufag** [comment]
I have implemented kohlchan's captcha mechanism when posting under proxy and VPN.
Check it.

**Comment by ganego** [comment]
I did _not_ test 6f9279059992b64aeeff6d5f9872d7beee3ceabb.

e0d1a200ef639b32b7a528780e0359dc7b4f941d: Bind ENTER to the _Send_ button please. Otherwise it seems to work <3
