### ISSUE TITLE
[Bug] Cannot fetch new posts on 4chan

### ISSUE THREAD

**Issue by atreval** [SthephanShinkufag/Dollchan-Extension-Tools#1473]
Using:
Opera GX (100.0.4815.82)
Tampermonkey (4.19.6183)
Dollchan Extension Tools (22.12.5.0)

Issue:
When loading a thread by pressing a "Entire thread" or auto get new posts in thread. Got "Connection failed (timeout)".
Exception in console - Uncaught (in promise) and object body.
The problem is only on 4chan boards.
All network security settings and filters are disabled in tampermonkey settings.

Video of issue: https://files.catbox.moe/6j9psn.mp4

Need advice, is this a problem on my client or a problem elsewhere?

**Comment by nashilnik** [comment]
I observe the same issue. Tested on both my main browser and a clean browser with a fresh installation of tampermonkey/dollchan.

Likely, because the `finalUrl` is missing the domain name.
![image](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/assets/17297106/c5aaec3e-2cb1-4e95-ab28-a7c8eb3cb43f)
