### ISSUE TITLE
Подгрузка постов со следующих страниц

### ISSUE THREAD

**Issue by mdilai** [SthephanShinkufag/Dollchan-Extension-Tools#625]
Я использую regex-ы для скрытия платины. Иногда ее так много, что на нулевой по 3-4 скрытых тредов и нулевая выглядит "бедно". Я хочу такую функцию, чтобы на место скрытых тредов можно было автоматически подгружать аналогичное колличество тредов со следующих страниц, чтобы нулевая всегда была "полной".

**Comment by SthephanShinkufag** [comment]
Неправильно назвал опцию.
На самом деле, треды берутся не со второй, а со следующих страниц, вплоть до четвёртой.

**Comment by SthephanShinkufag** [comment]
Added an option `"Filters"` > `"Load threads from next pages instead of hidden"`. If there are hidden threads on the first page, then the the same amount is loaded from the following pages (up to the fourth).

Добавлена опция `"Фильтры"` > `"Скрытые треды - загружать со следующих страниц"`. На первой странице вместо скрытых тредов автоматически подгружается аналогичное количество тредов со следующих страниц (вплоть до четвёртой). Опция по-умолчанию отключена.
