### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by ganego** [SthephanShinkufag/Dollchan-Extension-Tools#836]
Hey,
I tried asking them on iichan but the captcha there refuses to load (403) so I cannot post there.

I got two questions:
1) Why do some options have a star (\*) - what does this mean?
2) What is the difference between "Pre-load images\*" and "Download full version of images\*"?

Thank you for answering and especially for the whole script :)

**Comment by SthephanShinkufag** [comment]
1. It means that you need to reload page to apply that option.
2. "Pre-load images" adds ability to keep all full versions of images in browser's memory. Images keeps in `blob` format.  "Download full version of images" is the cheaper variation of pre-load. Browser directly downloads full versions and replaces them instead of thumbnails.

**Comment by ganego** [comment]
Thank you.
Is it possible (in Firefox) to give that blob a real name? Right now when for example I want to download a pic/webm with a 'real' name (aka not a number) I could right-click it and save it. The blob always has a number - I can change it of course when saving but having the 'real' name for standard would be better.

**Comment by SthephanShinkufag** [comment]
> Is it possible (in Firefox) to give that blob a real name

No.

**Comment by Y0ba** [comment]
@SthephanShinkufag Ну на самом деле в последнем коммите я частично решил эту проблему (хотя в развёрнутых картинках сохраняется всё ещё без имени и это не починить, потому что аттрибут `downlow` не работает в `img`).
